/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nonlineargradientsui;

/**
 *
 * @author Luminita Moruz
 */

import java.awt.event.ActionListener;
        
public class GradientTypePanel extends javax.swing.JPanel  {

    /**
     * Creates new form GradientTypePanel
     */
    public GradientTypePanel(ActionListener e) {
        initComponents();
        
        this.customButton.setActionCommand("Custom"); 
        this.customButton.addActionListener(e);
        
        this.ms1Button.setActionCommand("MS1"); 
        this.ms1Button.addActionListener(e);
        
        this.insilicoButton.setActionCommand("Insilico");
        this.insilicoButton.addActionListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientTypeGroup = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        insilicoButton = new javax.swing.JRadioButton();
        ms1Button = new javax.swing.JRadioButton();
        customButton = new javax.swing.JRadioButton();

        setMaximumSize(new java.awt.Dimension(570, 98));
        setMinimumSize(new java.awt.Dimension(570, 98));
        setPreferredSize(new java.awt.Dimension(570, 98));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type of nonlinear gradient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(560, 81));
        jPanel3.setMinimumSize(new java.awt.Dimension(560, 81));
        jPanel3.setPreferredSize(new java.awt.Dimension(560, 81));

        gradientTypeGroup.add(insilicoButton);
        insilicoButton.setSelected(true);
        insilicoButton.setText("In silico-optimized");
        insilicoButton.setToolTipText("");

        gradientTypeGroup.add(ms1Button);
        ms1Button.setText("MS1-optimized");
        ms1Button.setToolTipText("");

        gradientTypeGroup.add(customButton);
        customButton.setText("Custom distribution");
        customButton.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insilicoButton)
                .addGap(33, 33, 33)
                .addComponent(ms1Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(customButton)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(insilicoButton)
                    .addComponent(ms1Button)
                    .addComponent(customButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton customButton;
    private javax.swing.ButtonGroup gradientTypeGroup;
    private javax.swing.JRadioButton insilicoButton;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton ms1Button;
    // End of variables declaration//GEN-END:variables
}
