/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nonlineargradientsui;

/**
 *
 * @author luminitamoruz
 */
public class GradientOptionsPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public GradientOptionsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startGradientTimeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        endGradientTimeTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        startGradientBTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        endGradientBTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lagTimeTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timeStepTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        beforeTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        decimalsTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        separatorTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        afterTextField = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(570, 285));
        setMinimumSize(new java.awt.Dimension(570, 285));
        setPreferredSize(new java.awt.Dimension(570, 285));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Linear gradient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(560, 125));
        jPanel2.setMinimumSize(new java.awt.Dimension(560, 125));
        jPanel2.setPreferredSize(new java.awt.Dimension(560, 125));

        jLabel1.setText("Start gradient (LC time)");

        startGradientTimeTextField.setText("10");
        startGradientTimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGradientTimeTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("End gradient (LC time)");

        endGradientTimeTextField.setText("250");

        jLabel7.setText("Start gradient (%B)");

        startGradientBTextField.setText("2.0");

        jLabel8.setText("End gradient (%B)");

        endGradientBTextField.setText("40.0");

        jLabel9.setText("Lag (Raw time=LC time+lag)");

        lagTimeTextField.setText("6.2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startGradientTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endGradientTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lagTimeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endGradientBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startGradientBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(startGradientTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(startGradientBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(endGradientTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(endGradientBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lagTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(151, 151, 151))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nonlinear gradient parameters (Optional)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(560, 125));
        jPanel3.setMinimumSize(new java.awt.Dimension(560, 125));
        jPanel3.setPreferredSize(new java.awt.Dimension(560, 125));
        jPanel3.setRequestFocusEnabled(false);

        jLabel4.setText("Time step");

        jLabel6.setText("Text before <time>");

        jLabel10.setText("Decimals %B");

        jLabel11.setText("Separator");

        jLabel12.setText("Text after <%B>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeStepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(beforeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(afterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(decimalsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(separatorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(timeStepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(decimalsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(beforeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(separatorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(afterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(151, 151, 151))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void startGradientTimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGradientTimeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startGradientTimeTextFieldActionPerformed

    public void setDefaultValues(String defaultStartTime, String defaultEndTime, 
            String defaultStartB, String defaultEndB, String defaultLagTime, 
            String defaultTimeStep, String defaultDecimals, String defaultBefore,
            String defaultAfter, String defaultSeparator) {
        this.startGradientTimeTextField.setText(defaultStartTime);
        this.endGradientTimeTextField.setText(defaultEndTime);
        this.startGradientBTextField.setText(defaultStartB);
        this.endGradientBTextField.setText(defaultEndB);
        this.lagTimeTextField.setText(defaultLagTime);
        this.timeStepTextField.setText(defaultTimeStep);
        this.decimalsTextField.setText(defaultDecimals);
        this.beforeTextField.setText(defaultBefore);
        this.afterTextField.setText(defaultAfter);
        this.separatorTextField.setText(defaultSeparator);
    }   
    
    public Float getStartGradientTime() throws ValidationException { 
        String text = this.startGradientTimeTextField.getText();
        try {
            Float startTime = Float.parseFloat(text);
            return startTime;
        }
        catch (Exception e) {
            String message = "The start gradient time could not be parsed as a value";
            throw new ValidationException(message, "BAD_NUMBER");
        }          
    }
    
    public Float getEndGradientTime() throws ValidationException { 
        String text = this.endGradientTimeTextField.getText();
        try {
            Float endTime = Float.parseFloat(text);
            return endTime;
        }
        catch (Exception e) {
            String message = "The end gradient time could not be parsed as a value";
            throw new ValidationException(message, "BAD_NUMBER");
        }          
    }
    
    public Float getStartB() throws ValidationException { 
        String text = this.startGradientBTextField.getText();
        try {
            Float startB = Float.parseFloat(text);
            return startB;
        }
        catch (Exception e) {
            String message = "The start %B could not be parsed as a value";
            throw new ValidationException(message, "BAD_NUMBER");
        }          
    }
        
    public Float getEndB() throws ValidationException { 
        String text = this.endGradientBTextField.getText();
        try {
            Float endB = Float.parseFloat(text);
            return endB;
        }
        catch (Exception e) {
            String message = "The end %B could not be parsed as a value";
            throw new ValidationException(message, "BAD_NUMBER");
        }          
    }
     
    public Float getLagTime() throws ValidationException { 
        String text = this.lagTimeTextField.getText();
        try {
            Float lag = Float.parseFloat(text);
            return lag;
        }
        catch (Exception e) {
            String message = "The lag time could not be parsed as a value";
            throw new ValidationException(message, "BAD_NUMBER");
        }          
    }
    
    public Float getTimeStep() throws ValidationException { 
        String text = this.timeStepTextField.getText();
        try {
            Float ts = Float.parseFloat(text);
            return ts;
        }
        catch (Exception e) {
            String message = "The time step could not be parsed as a value";
            throw new ValidationException(message, "BAD_NUMBER");
        }          
    }
    
   public String getStringTimeStep() throws ValidationException { 
        return this.timeStepTextField.getText();        
    }
        
    public int getDecimals() throws ValidationException { 
        String text = this.decimalsTextField.getText();
        try {
            int d = Integer.parseInt(text);
            return d;
        }
        catch (Exception e) {
            String message = "The number of decimals could not be parsed as an integer value";
            throw new ValidationException(message, "BAD_NUMBER");
        }          
    }

    public String getBefore() { 
        String text = this.beforeTextField.getText();
        return text;
    }
    
    public String getAfter() { 
        String text = this.afterTextField.getText();
        return text;
    }
        
    public String getSeparator() { 
        String text = this.separatorTextField.getText();
        return text;
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField afterTextField;
    private javax.swing.JTextField beforeTextField;
    private javax.swing.JTextField decimalsTextField;
    private javax.swing.JTextField endGradientBTextField;
    private javax.swing.JTextField endGradientTimeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lagTimeTextField;
    private javax.swing.JTextField separatorTextField;
    private javax.swing.JTextField startGradientBTextField;
    private javax.swing.JTextField startGradientTimeTextField;
    private javax.swing.JTextField timeStepTextField;
    // End of variables declaration//GEN-END:variables
}
