/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nonlineargradientsui;

/**
 *
 * @author lumi
 */

import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;
import java.text.DecimalFormat;
import java.awt.Graphics;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class MzResultWindow extends javax.swing.JFrame {

    /**
     * Creates new form ResultWindow
     */
    public MzResultWindow() {     
        this.fileChooser = new JFileChooser();
        this.nMzDecimals = 2;
        this.nTimeDecimals = 0;
        this.optimizedMzWindows = new ArrayList<>();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mzWinsTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        imagePanel = new MzFigure(this.optimizedMzWindows);

        setTitle("Optimized m/z windows");
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mzWinsTextArea.setColumns(20);
        mzWinsTextArea.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        mzWinsTextArea.setRows(5);
        jScrollPane1.setViewportView(mzWinsTextArea);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel1.setText("Optimized m/z windows");

        jButton2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButton2.setText("Save m/z windows");
        jButton2.setActionCommand("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        imagePanel.setBackground(new java.awt.Color(255, 255, 255));
        imagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagePanel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(315, 315, 315)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setVariables(List<RtMzWindows> mzWins, int nTimeDecimals) {
        this.optimizedMzWindows.clear();
        this.optimizedMzWindows.addAll(mzWins);
        this.nTimeDecimals = nTimeDecimals;
        initTextArea();
        this.imagePanel.repaint();
    }
    
    private String getMz(List<Double> splits) {
        String res = "";
        String newline = System.getProperty("line.separator");
        char[] charsMz = new char[this.nMzDecimals];
	Arrays.fill(charsMz, '0');
	DecimalFormat dfMz = new DecimalFormat("#." + new String(charsMz));   
        
        for (int i = 0; i < splits.size()-1; ++i) {
            res += "[" + dfMz.format(splits.get(i)) + "," + dfMz.format(splits.get(i+1)) + "] ";
        }
        
        return res;
    
    }
    
    private void initTextArea() {
        String newline = System.getProperty("line.separator");
        List<String> text = new ArrayList<String>();
        char[] charsTime = new char[this.nTimeDecimals];
	Arrays.fill(charsTime, '0');
	DecimalFormat dfTime = new DecimalFormat("#." + new String(charsTime));     
        String line, st, et;
        RtMzWindows tmp;
        
        
        text.add("Time-interval(MS-times)\tMz_windows" + newline);
        for (int i = 0; i < this.optimizedMzWindows.size(); ++i) {
            tmp = this.optimizedMzWindows.get(i);                 
            st = dfTime.format(tmp.getStartRT());
            et = dfTime.format(tmp.getEndRT());
            
            if (this.nTimeDecimals == 0) {
                st = ""  + Math.round(tmp.getStartRT()); 
                et = ""  + Math.round(tmp.getEndRT()); 
            }
            line = st + ", " + et + "\t";
            text.add(line + getMz(tmp.getSplits()) + newline);      
        } 
        this.mzWinsTextArea.setText(ResultWindow.concatenateArrayList(text));
  }
          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        //System.out.println(this.gradientFunction);
    }//GEN-LAST:event_jButton1ActionPerformed

    private int writeToFile(File f) {
        FileWriter fileHandler;
        
        try {
            fileHandler = new FileWriter(f);
            String lines = this.mzWinsTextArea.getText();
            fileHandler.write(lines);
            fileHandler.close();
        }
        catch (IOException e) {
            return 1;
        }
        return 0;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int returnVal = this.fileChooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File path = fileChooser.getSelectedFile();
            if (path.exists() && !path.isDirectory()) {
                int n = JOptionPane.showConfirmDialog(this, "File exists, are you sure you want "
                        + "to overwrite?", "Overwrite", JOptionPane.YES_NO_OPTION);
                if (n != JOptionPane.YES_OPTION) {
                    return;
                }                
            }   
            int ret = this.writeToFile(path);
            if (ret != 0) {
                JOptionPane.showMessageDialog(this, "ERROR: could not write to " +
                        path.getName() + ". Please make sure you have write permissions " +
                        "and that you provided a valid filename, then try again.", 
                        "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "M/z windows saved successfully to " +
                        path.getName(), "SAVED", JOptionPane.INFORMATION_MESSAGE);                
            }
            
        } else {
            System.out.println("Save command cancelled by user.\n");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MzResultWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MzResultWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MzResultWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MzResultWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                List<Double> mz1 = new ArrayList<>();
                mz1.add(100.0);
                mz1.add(130.0);
                mz1.add(200.0);
                
                List<Double> mz2 = new ArrayList<>();
                mz2.add(100.0);
                mz2.add(160.0);
                mz2.add(200.0);
                        
 
                List<Double> mz3 = new ArrayList<>();
                mz3.add(100.0);
                mz3.add(190.0);
                mz3.add(200.0);
                
                List<RtMzWindows> mzWins = new ArrayList<>();
                mzWins.add(new RtMzWindows((float)10.0,(float)30.0, mz1));
                mzWins.add(new RtMzWindows((float)30.0,(float)60.0, mz2));
                mzWins.add(new RtMzWindows((float)60.0,(float)90.0, mz3));
                
                MzResultWindow mzw = new MzResultWindow();
                mzw.setVisible(false);
                mzw.setVariables(mzWins, 1);
                mzw.repaint();
               
                mzw.setVisible(true);
            }
        });
    }

    // the optimized m/z windows  
    List<RtMzWindows> optimizedMzWindows;
    // number of decimas of the m/z
    final int nMzDecimals;
    // number of decimals of the time 
    int nTimeDecimals;
    final JFileChooser fileChooser;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mzWinsTextArea;
    // End of variables declaration//GEN-END:variables
}
